// TransactionCategory.js
export const TransactionCategory = {
  Food: "Food",
  Drinks: "Drinks",
  Rent: "Rent",
  Utilities: "Utilities",
  Groceries: "Groceries",
  Entertainment: "Entertainment",
  Transportation: "Transportation",
  HealthAndFitness: "Health and Fitness",
  PersonalCare: "Personal Care",
  Shopping: "Shopping",
  Travel: "Travel",
  HomeImprovement: "Home Improvement",
  Education: "Education",
  Charity: "Charity",
  MedicalAndHealthcare: "Medical and Healthcare",
  HomeServices: "Home Services",
  PetCare: "Pet Care",
  GiftsAndDonations: "Gifts and Donations",
  Investments: "Investments",
  Savings: "Savings",
  PersonalFinance: "Personal Finance",
  BusinessFinance: "Business Finance",
  Taxes: "Taxes",
  Insurance: "Insurance",
};
